[
{"text":"What is your favorite way to be surprised?"},
{"text":"Which song reminds you of us the most?"},
{"text":"Ideal date night: indoor or outdoor?"},
{"text":"What color do you love wearing the most?"},
{"text":"Morning kisses or goodnight hugs?"},
{"text":"Tea, coffee, or hot chocolate?"},
{"text":"Beach holiday or mountain cabin?"},
{"text":"Texting or voice notes?"},
{"text":"What’s your love language?"},
{"text":"What snack do you always crave?"},
  "Do you enjoy sharing your favorite childhood memories?",
  "Favorite way to celebrate small victories together?",
  "Do you like morning walks hand-in-hand?",
  "Favorite way to unwind after a long day?",
  "Do you enjoy planning surprise date nights?",
  "Favorite cozy activity for rainy days?",
  "Do you like sending cute messages randomly?",
  "Favorite shared hobby to relax together?",
  "Do you enjoy late-night conversations?",
  "Favorite way to make each other smile daily?",
  "Do you like leaving surprise notes in pockets or bags?",
  "Favorite playful activity to do indoors?",
  "Do you enjoy watching sunsets together?",
  "Favorite way to connect emotionally on busy days?",
  "Do you like exchanging small gifts occasionally?",
  "Favorite indoor activity to enjoy as a couple?",
  "Do you enjoy storytelling or sharing fantasies together?",
  "Favorite playful memory from the past month?",
  "Do you like spontaneous hugs and kisses?",
  "Favorite romantic breakfast idea?",
  "Do you enjoy dancing together at home?",
  "Favorite way to celebrate anniversaries creatively?",
  "Do you like planning weekend mini-adventures?",
  "Favorite cozy spot at home for both of you?",
  "Do you enjoy exploring new restaurants together?",
  "Favorite way to make ordinary days special?",
  "Do you like exchanging sweet messages during the day?",
  "Favorite playful activity outdoors?",
  "Do you enjoy indoor cozy activities together?",
  "Favorite way to surprise your partner creatively?",
  "Do you like baking or cooking new meals together?",
  "Favorite romantic movie scene to watch together?",
  "Do you enjoy planning couple traditions?",
  "Favorite way to make each other laugh unexpectedly?",
  "Do you like morning or evening cuddles?",
  "Favorite shared hobby for fun weekends?",
  "Do you enjoy weekend trips together spontaneously?",
  "Favorite way to express love physically?",
  "Do you like sending voice messages randomly?",
  "Favorite playful teasing moment?",
  "Do you enjoy creating handmade gifts together?",
  "Favorite way to connect emotionally in the evening?",
  "Do you like planning couple creative projects?",
  "Favorite cozy indoor activity for weekends?",
  "Do you enjoy spontaneous outings together?",
  "Favorite way to celebrate love daily?",
  "Do you like leaving love notes unexpectedly?",
  "Favorite playful activity to break routine?",
  "Do you enjoy watching sunrises together?",
  "Favorite way to spend quiet evenings together?",
  "Do you like decorating together for festive occasions?",
  "Favorite way to laugh together daily?",
  "Do you enjoy cooking themed meals together?",
  "Favorite romantic gesture unexpectedly?",
  "Do you like morning rituals together?",
  "Favorite cozy memory from trips?",
  "Do you enjoy indoor games or puzzles together?",
  "Favorite way to celebrate small achievements?",
  "Do you like planning mini-adventures?",
  "Favorite way to show appreciation daily?",
  "Do you enjoy spontaneous romantic gestures?",
  "Favorite way to connect after a long day?",
  "Do you like exchanging cute messages?",
  "Favorite playful moment outdoors?",
  "Do you enjoy creative couple date nights?",
  "Favorite cozy corner to spend time together?",
  "Do you like leaving surprise notes for each other?",
  "Favorite way to make each other feel loved daily?",
  "Do you enjoy weekend indoor activities?",
  "Favorite shared hobby for relaxation?",
  "Do you like celebrating little wins together?",
  "Favorite romantic gesture that means a lot?",
  "Do you enjoy weekend creative projects?",
  "Favorite way to connect emotionally after work?",
  "Do you like planning couple activities creatively?",
  "Favorite playful activity indoors or outdoors?",
  "Do you enjoy spontaneous gifts for each other?",
  "Favorite way to make ordinary moments memorable?",
  "Do you like morning cuddles or evening kisses?",
  "Favorite playful challenge to do together?",
  "Do you enjoy quiet walks together?",
  "Favorite way to share laughter daily?",
  "Do you like exchanging handwritten love notes?",
  "Favorite cozy indoor activity on rainy days?",
  "Do you enjoy playful competitions together?",
  "Favorite way to celebrate your relationship creatively?",
  "Do you like decorating for seasonal celebrations?",
  "Favorite playful gesture to make them smile?",
  "Do you enjoy creating couple traditions?",
  "Favorite way to celebrate love daily?",
  "Do you like sending unexpected messages?",
  "Favorite romantic breakfast or meal together?",
  "Do you enjoy indoor cozy activities with music?",
  "Favorite way to unwind together after work?",
  "Do you like spontaneous couple adventures?",
  "Favorite playful activity for weekends?",
  "Do you enjoy sharing favorite books or movies?",
  "Favorite way to express love without words?",
  "Do you like planning couple projects creatively?",
  "Favorite way to make small moments special?",
  "Do you enjoy quiet mornings together?",
  "Favorite playful activity to break routine?",
  "Do you like baking or cooking together for fun?",
  "Favorite cozy corner at home for couple time?",
  "Do you enjoy sending love notes randomly?",
  "Favorite way to connect emotionally daily?",
  "Do you like spontaneous date nights creatively?",
  "Favorite way to make each other smile unexpectedly?",
  "Do you enjoy sharing favorite memories together?",
  "Favorite playful indoor or outdoor activity?",
  "Do you like celebrating milestones creatively?",
  "Favorite romantic gesture to do unexpectedly?",
  "Do you enjoy quiet evenings at home together?",
  "Favorite playful challenge that makes you laugh?",
  "Favorite way to celebrate quiet moments together?",
  "Do you enjoy morning walks hand-in-hand?",
  "Favorite way to make each other feel appreciated?",
  "Do you like sharing favorite quotes?",
  "Favorite playful teasing moment?",
  "Do you enjoy spontaneous hugs and kisses?",
  "Favorite way to spend a rainy afternoon together?",
  "Do you like creating shared playlists?",
  "Favorite way to express love in words?",
  "Do you enjoy cooking themed meals together?",
  "Favorite way to show affection unexpectedly?",
  "Do you like quiet evenings reading together?",
  "Favorite playful game to play together?",
  "Do you enjoy writing notes for each other?",
  "Favorite way to connect after work?",
  "Do you like surprise breakfast in bed?",
  "Favorite cozy indoor activity on weekends?",
  "Do you enjoy decorating your space together?",
  "Favorite way to celebrate anniversaries creatively?",
  "Do you like sending unexpected messages?",
  "Favorite shared hobby to relax?",
  "Do you enjoy morning cuddles?",
  "Favorite way to laugh together?",
  "Do you like planning fun couple activities?",
  "Favorite playful moment outdoors?",
  "Do you enjoy spontaneous adventures together?",
  "Favorite way to express love physically?",
  "Do you like exchanging small handmade gifts?",
  "Favorite way to spend Sunday mornings together?",
  "Do you enjoy planning creative dates?",
  "Favorite way to send love notes?",
  "Do you like late-night talks and laughter?",
  "Favorite relaxing activity after a long day?",
  "Do you enjoy dancing together at home?",
  "Favorite shared memory from trips?",
  "Do you like leaving sweet notes for each other?",
  "Favorite way to celebrate small victories together?",
  "Do you enjoy watching sunrises together?",
  "Favorite cozy spot for couple time?",
  "Do you like spontaneous picnics or outings?",
  "Favorite way to surprise your partner?",
  "Do you enjoy planning weekend adventures?",
  "Favorite way to communicate love?",
  "Do you like singing silly songs together?",
  "Favorite quiet activity to enjoy as a couple?",
  "Do you enjoy decorating for festive occasions?",
  "Favorite playful gesture that makes you laugh?",
  "Do you like sharing favorite snacks?",
  "Favorite way to make ordinary days special?",
  "Do you enjoy creating new couple traditions?",
  "Favorite romantic gesture to do unexpectedly?",
  "Do you like morning or evening cuddles?",
  "Favorite way to unwind on weekends?",
  "Do you enjoy exploring nature together?",
  "Favorite shared hobby indoors?",
  "Do you like sending cute messages throughout the day?",
  "Favorite playful activity to break routine?",
  "Do you enjoy creating surprises for each other?",
  "Favorite way to celebrate love daily?",
  "Do you like writing love letters occasionally?",
  "Favorite relaxing spot in your home?",
  "Do you enjoy weekend trips together?",
  "Favorite way to make each other laugh daily?",
  "Do you like surprise date nights?",
  "Favorite romantic meal to share?",
  "Do you enjoy indoor games together?",
  "Favorite way to connect emotionally?",
  "Do you like sharing your favorite memories?",
  "Favorite playful activity at home?",
  "Do you enjoy quiet mornings with coffee together?",
  "Favorite way to send a love message?",
  "Do you like decorating your space together?",
  "Favorite cozy evening activity?",
  "Do you enjoy dancing or singing together?",
  "Favorite way to make small moments special?",
  "Do you like spontaneous gift-giving?",
  "Favorite shared hobby for relaxation?",
  "Do you enjoy exploring new hobbies together?",
  "Favorite way to surprise your partner creatively?",
  "Do you like watching sunsets together?",
  "Favorite way to show love without words?",
  "Do you enjoy planning couple rituals?",
  "Favorite playful teasing moment?",
  "Do you like celebrating little achievements together?",
  "Favorite relaxing activity to do together?",
  "Do you enjoy leaving surprise notes for each other?",
  "Favorite way to connect emotionally in the evening?",
  "Do you like morning cuddles or evening hugs?",
  "Favorite playful activity outdoors?",
  "Do you enjoy indoor cozy activities?",
  "Favorite way to celebrate your relationship creatively?",
  "Do you like planning small surprises?",
  "Favorite way to make each other feel loved daily?",
  "Do you enjoy weekend indoor activities?",
  "Favorite romantic gesture that means a lot?",
  "Do you like spontaneous outings?",
  "Favorite way to share laughter together?",
  "Do you enjoy quiet walks together?",
  "Favorite playful memory you both cherish?",
  "Do you like writing notes for each other unexpectedly?",
  "Favorite way to spend quality time at home?",
  "Do you enjoy creative date nights?",
  "Favorite shared hobby outdoors?",
  "Do you like morning or evening rituals together?",
  "Favorite way to express love physically?",
  "Do you enjoy playful competitions together?",
  "Favorite way to make ordinary moments memorable?",
  "Do you like planning couple adventures?",
  "Favorite cozy indoor memory together?",
  "Do you enjoy spontaneous romantic gestures?",
  "Favorite way to stay connected during busy days?",
  "Do you like decorating for seasonal celebrations?",
  "Favorite way to surprise your partner at home?",
  "Do you enjoy making each other laugh unexpectedly?",
  "Favorite romantic memory from a trip?",
  "Do you like quiet evenings with music together?",
  "Favorite way to celebrate your love daily?",
  "Do you enjoy playful challenges together?",
  "Favorite shared creative activity?",
  "Do you like morning or evening love notes?",
  "Favorite way to make each other feel appreciated?",
  "Do you enjoy weekend adventures spontaneously?",
  "Favorite playful gesture to make them smile?",
  "Do you like cooking or baking together?",
  "Favorite cozy corner to spend time together?",
  "Do you enjoy sharing favorite movies?",
  "Favorite way to express affection without words?",
  "Do you like planning couple activities creatively?",
  "Favorite way to celebrate special moments?",
  "Do you enjoy indoor games or puzzles together?",
  "Favorite playful moment that made you laugh?",
  "Do you like spontaneous date nights?",
  "Favorite way to unwind with your partner?",
  "Do you enjoy storytelling or sharing fantasies?",
  "Favorite shared hobby for fun weekends?",
  "Do you like leaving surprise messages?",
  "Favorite cozy activity for rainy days?",
  "Do you enjoy celebrating love creatively?",
  "Favorite playful activity to break routine?",
  "Do you like exchanging small gifts occasionally?",
  "Favorite way to make ordinary days special?",
  "Do you enjoy planning couple rituals?",
  "Favorite romantic gesture to do unexpectedly?",
  "Do you like morning cuddles or evening kisses?",
  "Favorite way to connect emotionally after work?",
  "Do you enjoy weekend creative projects together?",
  "Favorite playful activity indoors or outdoors?",
  "Do you like celebrating small wins as a couple?",
  "Favorite way to show love daily?",
  "Favorite way to celebrate anniversaries together?",
  "Do you enjoy early morning cuddles?",
  "Favorite way to spend lazy afternoons?",
  "Do you like planning fun weekends?",
  "Favorite romantic song to share?",
  "Do you enjoy evening walks together?",
  "Favorite way to spend holidays creatively?",
  "Do you like leaving sweet notes for each other?",
  "Favorite couple activity on rainy days?",
  "Do you enjoy watching movies together?",
  "Favorite way to surprise your partner?",
  "Do you like sending love texts randomly?",
  "Favorite indoor activity together?",
  "Do you enjoy stargazing at night?",
  "Favorite way to spend a cozy evening?",
  "Do you like planning trips together?",
  "Favorite playful activity as a couple?",
  "Do you enjoy cooking new recipes together?",
  "Favorite way to relax on weekends?",
  "Do you like sharing secret messages?",
  "Favorite way to connect emotionally?",
  "Do you enjoy singing together?",
  "Favorite way to start the day together?",
  "Do you like writing love letters?",
  "Favorite spontaneous adventure?",
  "Do you enjoy baking together?",
  "Favorite quiet activity at home?",
  "Do you like sharing favorite memories?",
  "Favorite way to celebrate small wins?",
  "Do you enjoy morning walks?",
  "Favorite way to make your partner smile?",
  "Do you like exchanging gifts unexpectedly?",
  "Favorite cozy corner at home?",
  "Do you enjoy planning surprises?",
  "Favorite way to spend evenings together?",
  "Do you like watching sunsets?",
  "Favorite way to express love creatively?",
  "Do you enjoy playing games together?",
  "Favorite romantic movie to watch together?",
  "Do you like late-night talks?",
  "Favorite way to celebrate birthdays?",
  "Do you enjoy creating couple traditions?",
  "Favorite way to spend weekend mornings?",
  "Do you like planning date nights?",
  "Favorite way to connect after a long day?",
  "Do you enjoy spontaneous picnics?",
  "Favorite shared hobby?",
  "Do you like giving compliments randomly?",
  "Favorite way to laugh together?",
  "Do you enjoy planning future adventures?",
  "Favorite way to show affection physically?",
  "Do you like writing little notes for each other?",
  "Favorite way to unwind in the evening?",
  "Do you enjoy exploring new places?",
  "Favorite activity to do on weekends?",
  "Do you like sharing favorite books?",
  "Favorite way to celebrate milestones?",
  "Do you enjoy cooking together on weekends?",
  "Favorite way to express love daily?",
  "Do you like morning cuddles?",
  "Favorite way to spend cozy nights?",
  "Do you enjoy decorating together?",
  "Favorite playful activity together?",
  "Do you like exchanging handwritten notes?",
  "Favorite way to support each other emotionally?",
  "Do you enjoy late-night drives?",
  "Favorite way to make memories together?",
  "Do you like sending voice messages?",
  "Favorite way to spend Sundays together?",
  "Do you enjoy watching sunrises?",
  "Favorite way to celebrate achievements?",
  "Do you like planning couple projects?",
  "Favorite way to connect emotionally after work?",
  "Do you enjoy creative date nights?",
  "Favorite relaxing activity together?",
  "Do you like sending cute messages?",
  "Favorite way to share laughter?",
  "Do you enjoy spontaneous fun activities?",
  "Favorite way to make each other feel special?",
  "Do you like planning romantic surprises?",
  "Favorite way to express gratitude?",
  "Do you enjoy baking or cooking new meals together?",
  "Favorite couple game to play?",
  "Do you like morning rituals together?",
  "Favorite way to celebrate love creatively?",
  "Do you enjoy storytelling together?",
  "Favorite way to unwind after a busy day?",
  "Do you like decorating for festive seasons?",
  "Favorite indoor activity to enjoy together?",
  "Do you enjoy sharing songs or playlists?",
  "Favorite way to send a love note?",
  "Do you like planning mini-adventures?",
  "Favorite romantic breakfast idea?",
  "Do you enjoy evening walks in the park?",
  "Favorite way to surprise your partner?",
  "Do you like exchanging small gifts randomly?",
  "Favorite playful moment together?",
  "Do you enjoy singing or dancing together?",
  "Favorite way to make each other laugh unexpectedly?",
  "Do you like quiet nights at home together?",
  "Favorite shared hobby for fun?",
  "Do you enjoy late-night talks in bed?",
  "Favorite way to celebrate relationship milestones?",
  "Do you like planning spontaneous trips?",
  "Favorite cozy indoor activity?",
  "Do you enjoy exploring new restaurants together?",
  "Favorite way to connect during busy days?",
  "Do you like making handmade gifts?",
  "Favorite way to spend holidays creatively?",
  "Do you enjoy morning coffee together?",
  "Favorite way to show love without words?",
  "Do you like creative surprises?",
  "Favorite way to spend an evening together?",
  "Do you enjoy writing love notes?",
  "Favorite shared memory?",
  "Do you like celebrating small achievements together?",
  "Favorite playful activity to do together?",
  "Do you enjoy watching romantic movies?",
  "Favorite way to express love physically?",
  "Do you like exchanging sweet messages during the day?",
  "Favorite way to spend quiet mornings together?",
  "Do you enjoy planning couple activities?",
  "Favorite indoor game to play together?",
  "Do you like spontaneous gifts for each other?",
  "Favorite way to connect emotionally at night?",
  "Do you enjoy sharing favorite meals together?",
  "Favorite way to unwind together after work?",
  "Do you like making each other laugh daily?",
  "Favorite romantic gesture?",
  "Do you enjoy long walks together?",
  "Favorite way to celebrate each other’s achievements?",
  "Do you like leaving surprise notes?",
  "Favorite cozy spot for both of you?",
  "Do you enjoy weekend adventures together?",
  "Favorite way to start the day as a couple?",
  "Do you like baking or cooking for each other?",
  "Favorite playful activity indoors?",
  "Do you enjoy late-night phone calls?",
  "Favorite way to celebrate love creatively?",
  "Do you like planning couple outings?",
  "Favorite relaxing activity after work?",
  "Do you enjoy sharing hobbies together?",
  "Favorite way to celebrate quiet moments together?",
  "Do you enjoy morning walks hand-in-hand?",
  "Favorite way to make each other feel appreciated?",
  "Do you like sharing favorite quotes?",
  "Favorite playful teasing moment?",
  "Do you enjoy spontaneous hugs and kisses?",
  "Favorite way to spend a rainy afternoon together?",
  "Do you like creating shared playlists?",
  "Favorite way to express love in words?",
  "Do you enjoy cooking themed meals together?",
  "Favorite way to show affection unexpectedly?",
  "Do you like quiet evenings reading together?",
  "Favorite playful game to play together?",
  "Do you enjoy writing notes for each other?",
  "Favorite way to connect after work?",
  "Do you like surprise breakfast in bed?",
  "Favorite cozy indoor activity on weekends?",
  "Do you enjoy decorating your space together?",
  "Favorite way to celebrate anniversaries creatively?",
  "Do you like sending unexpected messages?",
  "Favorite shared hobby to relax?",
  "Do you enjoy morning cuddles?",
  "Favorite way to laugh together?",
  "Do you like planning fun couple activities?",
  "Favorite playful moment outdoors?",
  "Do you enjoy spontaneous adventures together?",
  "Favorite way to express love physically?",
  "Do you like exchanging small handmade gifts?",
  "Favorite way to spend Sunday mornings together?",
  "Do you enjoy planning creative dates?",
  "Favorite way to send love notes?",
  "Do you like late-night talks and laughter?",
  "Favorite relaxing activity after a long day?",
  "Do you enjoy dancing together at home?",
  "Favorite shared memory from trips?",
  "Do you like leaving sweet notes for each other?",
  "Favorite way to celebrate small victories together?",
  "Do you enjoy watching sunrises together?",
  "Favorite cozy spot for couple time?",
  "Do you like spontaneous picnics or outings?",
  "Favorite way to surprise your partner?",
  "Do you enjoy planning weekend adventures?",
  "Favorite way to communicate love?",
  "Do you like singing silly songs together?",
  "Favorite quiet activity to enjoy as a couple?",
  "Do you enjoy decorating for festive occasions?",
  "Favorite playful gesture that makes you laugh?",
  "Do you like sharing favorite snacks?",
  "Favorite way to make ordinary days special?",
  "Do you enjoy creating new couple traditions?",
  "Favorite romantic gesture to do unexpectedly?",
  "Do you like morning or evening cuddles?",
  "Favorite way to unwind on weekends?",
  "Do you enjoy exploring nature together?",
  "Favorite shared hobby indoors?",
  "Do you like sending cute messages throughout the day?",
  "Favorite playful activity to break routine?",
  "Do you enjoy creating surprises for each other?",
  "Favorite way to celebrate love daily?",
  "Do you like writing love letters occasionally?",
  "Favorite relaxing spot in your home?",
  "Do you enjoy weekend trips together?",
  "Favorite way to make each other laugh daily?",
  "Do you like surprise date nights?",
  "Favorite romantic meal to share?",
  "Do you enjoy indoor games together?",
  "Favorite way to connect emotionally?",
  "Do you like sharing your favorite memories?",
  "Favorite playful activity at home?",
  "Do you enjoy quiet mornings with coffee together?",
  "Favorite way to send a love message?",
  "Do you like decorating your space together?",
  "Favorite cozy evening activity?",
  "Do you enjoy dancing or singing together?",
  "Favorite way to make small moments special?",
  "Do you like spontaneous gift-giving?",
  "Favorite shared hobby for relaxation?",
  "Do you enjoy exploring new hobbies together?",
  "Favorite way to surprise your partner creatively?",
  "Do you like watching sunsets together?",
  "Favorite way to show love without words?",
  "Do you enjoy planning couple rituals?",
  "Favorite playful teasing moment?",
  "Do you like celebrating little achievements together?",
  "Favorite relaxing activity to do together?",
  "Do you enjoy leaving surprise notes for each other?",
  "Favorite way to connect emotionally in the evening?",
  "Do you like morning cuddles or evening hugs?",
  "Favorite playful activity outdoors?",
  "Do you enjoy indoor cozy activities?",
  "Favorite way to celebrate your relationship creatively?",
  "Do you like planning small surprises?",
  "Favorite way to make each other feel loved daily?",
  "Do you enjoy weekend indoor activities?",
  "Favorite romantic gesture that means a lot?",
  "Do you like spontaneous outings?",
  "Favorite way to share laughter together?",
  "Do you enjoy quiet walks together?",
  "Favorite playful memory you both cherish?",
  "Do you like writing notes for each other unexpectedly?",
  "Favorite way to spend quality time at home?",
  "Do you enjoy creative date nights?",
  "Favorite shared hobby outdoors?",
  "Do you like morning or evening rituals together?",
  "Favorite way to express love physically?",
  "Do you enjoy playful competitions together?",
  "Favorite way to make ordinary moments memorable?",
  "Do you like planning couple adventures?",
  "Favorite cozy indoor memory together?",
  "Do you enjoy spontaneous romantic gestures?",
  "Favorite way to stay connected during busy days?",
  "Do you like decorating for seasonal celebrations?",
  "Favorite way to surprise your partner at home?",
  "Do you enjoy making each other laugh unexpectedly?",
  "Favorite romantic memory from a trip?",
  "Do you like quiet evenings with music together?",
  "Favorite way to celebrate your love daily?",
  "Do you enjoy playful challenges together?",
  "Favorite shared creative activity?",
  "Do you like morning or evening love notes?",
  "Favorite way to make each other feel appreciated?",
  "Do you enjoy weekend adventures spontaneously?",
  "Favorite playful gesture to make them smile?",
  "Do you like cooking or baking together?",
  "Favorite cozy corner to spend time together?",
  "Do you enjoy sharing favorite movies?",
  "Favorite way to express affection without words?",
  "Do you like planning couple activities creatively?",
  "Favorite way to celebrate special moments?",
  "Do you enjoy indoor games or puzzles together?",
  "Favorite playful moment that made you laugh?",
  "Do you like spontaneous date nights?",
  "Favorite way to unwind with your partner?",
  "Do you enjoy storytelling or sharing fantasies?",
  "Favorite shared hobby for fun weekends?",
  "Do you like leaving surprise messages?",
  "Favorite cozy activity for rainy days?",
  "Do you enjoy celebrating love creatively?",
  "Favorite playful activity to break routine?",
  "Do you like exchanging small gifts occasionally?",
  "Favorite way to make ordinary days special?",
  "Do you enjoy planning couple rituals?",
  "Favorite romantic gesture to do unexpectedly?",
  "Do you like morning cuddles or evening kisses?",
  "Favorite way to connect emotionally after work?",
  "Do you enjoy weekend creative projects together?",
  "Favorite playful activity indoors or outdoors?",
  "Do you like celebrating small wins as a couple?",

  "Do you like role-playing fun scenarios?",
  "Favorite way to say 'I miss you'?",
  "Do you like sending cute messages during work?",
  "Favorite romantic holiday memory?",
  "Do you enjoy planning themed date nights?",
  "Favorite time to relax together?",
  "Do you like spontaneous road trips?",
  "Favorite thing about our first date?",
  "Do you enjoy baking or cooking together?",
  "Favorite way to spend rainy days together?",
  "Do you like surprising each other with notes?",
  "Favorite love song for us?",
  "Do you enjoy doing puzzles together?",
  "Favorite physical gesture that makes you feel loved?",
  "Do you like singing silly songs together?",
  "Favorite romantic TV show moment?",
  "Do you enjoy working on home projects together?",
  "Favorite way to spend Sunday mornings?",
  "Do you like sending voice messages instead of texts?",
  "Favorite compliment you received from me?",
  "Do you enjoy watching sunsets while holding hands?",
  "Favorite vacation spot together?",
  "Do you like decorating for special days together?",
  "Favorite way to celebrate anniversaries creatively?",
  "Do you enjoy exploring parks or nature trails together?",
  "Favorite scent that reminds you of me?",
  "Do you like dressing up for fun occasions together?",
  "Favorite way to unwind after a long day together?",
  "Do you enjoy spontaneous mini-gifts?",
  "Favorite way to resolve small conflicts lovingly?",
  "Do you like writing little notes in pockets or bags?",
  "Favorite quiet activity at home together?",
  "Do you enjoy early morning walks together?",
  "Favorite way to celebrate unexpected achievements?",
  "Do you like exchanging small surprises randomly?",
  "Favorite place to cuddle at home?",
  "Do you enjoy making playlists for each other?",
  "Favorite way to spend a lazy weekend together?",
  "Do you like sharing secrets about dreams and goals?",
  "Favorite way to laugh together?",
  "Do you enjoy reminiscing old memories together?",
  "Favorite affectionate nickname for me?",
  "Do you like spontaneous picnics?",
  "Favorite way to motivate each other?",
  "Do you enjoy storytelling or sharing fantasies together?",
  "Favorite place to go shopping together?",
  "Do you like taking turns planning surprise dates?",
  "Favorite way to say 'I love you' creatively?",
  "Do you enjoy sketching or doodling together?",
  "Favorite morning ritual as a couple?",
  "Do you like creating your own couple traditions?",
  "Favorite way to keep connected during busy days?",
  "Do you enjoy singing along to radio songs together?",
  "Favorite way to celebrate small wins in life?",
  "Do you like morning coffee or tea together?",
  "Favorite thing to do spontaneously on weekends?",
  "Do you enjoy sharing dreams and future plans?",
  "Favorite romantic movie scene we relate to?",
  "Do you like surprise notes left in unexpected places?",
  "Favorite way to enjoy each other’s company quietly?",
  "Do you enjoy planning trips together online?",
  "Favorite way to tease each other playfully?",
  "Do you like making each other laugh unexpectedly?",
  "Favorite way to spend evening walks together?",
  "Do you enjoy doing volunteer or charity work together?",
  "Favorite way to decorate for festive seasons together?",
  "Do you like giving each other massages after a long day?",
  "Favorite way to enjoy weekends indoors together?",
  "Do you enjoy trying new activities or sports together?",
  "Favorite time of day to relax together?",
  "Do you like having inside jokes as a couple?",
  "Favorite way to exchange handwritten notes secretly?",
  "Do you enjoy late-night talks together?",
  "Favorite shared inside joke?",
  "Do you like sharing your favorite books?",
  "Favorite game to play together?",
  "Do you enjoy going to the theater together?",
  "Favorite way to celebrate small victories?",
  "Do you like giving each other compliments randomly?",
  "Favorite way to support each other emotionally?",
  "Do you enjoy watching sunsets on trips?",
  "Favorite way to spend holidays together?",
  "Do you like creating couple scrapbooks?",
  "Favorite way to surprise each other?",
  "Do you enjoy making handmade gifts?",
  "Favorite shared cooking recipe?",
  "Do you like writing love notes in the morning?",
  "Favorite way to show appreciation daily?",
  "Do you enjoy planning dream vacations together?",
  "Favorite relaxing activity for weekends?",
  "Do you like morning cuddles?",
  "Favorite way to spend quiet evenings together?",
  "Do you like sharing music playlists?",
  "Favorite way to start a weekend morning?",
  "Do you enjoy morning stretches together?",
  "Favorite way to celebrate a new achievement?",
  "Do you like giving unexpected gifts?",
  "Favorite spot for cozy cuddles?",
  "Do you enjoy listening to audiobooks together?",
  "Favorite way to reconnect after a busy day?",
  "Do you like planning surprise dates?",
  "Favorite couple photo pose?",
  "Do you enjoy walking hand-in-hand?",
  "Favorite way to relax on Sundays?",
  "Do you like cooking themed meals together?",
  "Favorite way to celebrate anniversaries at home?",
  "Do you enjoy late-night drives together?",
  "Favorite shared hobby for weekends?",
  "Do you like decorating for holidays together?",
  "Favorite way to motivate each other?",
  "Do you enjoy morning coffee rituals?",
  "Favorite way to send love messages?",
  "Do you like making scrapbooks together?",
  "Favorite shared adventure memory?",
  "Do you enjoy learning new skills together?",
  "Favorite quiet activity for rainy days?",
  "Do you like leaving surprise notes for each other?",
  "Favorite way to express affection physically?",
  "Do you enjoy morning walks in nature?",
  "Favorite way to celebrate small wins together?",
  "Do you like taking spontaneous trips?",
  "Favorite way to unwind after work?",
  "Do you enjoy creating art together?",
  "Favorite romantic breakfast idea?",
  "Do you like dancing at home together?",
  "Favorite way to support each other emotionally?",
  "Do you enjoy watching sunrises together?",
  "Favorite way to spend a cozy night in?",
  "Do you like sharing your favorite snacks?",
  "Favorite way to say 'I love you' creatively?",
  "Do you enjoy stargazing together?",
  "Favorite memory from a trip together?",
  "Do you like sending cute voice notes?",
  "Favorite way to show appreciation daily?",
  "Do you enjoy trying new restaurants together?",
  "Favorite couple game to play?",
  "Do you like morning cuddles?",
  "Favorite way to celebrate birthdays creatively?",
  "Do you enjoy watching movies under blankets?",
  "Favorite way to cheer each other up?",
  "Do you like creating traditions together?",
  "Favorite quiet weekend activity?",
  "Do you enjoy taking photos of each other?",
  "Favorite way to connect after a long day?",
  "Do you like sending handwritten letters?",
  "Favorite activity to do together outdoors?",
  "Do you enjoy dancing in the living room?",
  "Favorite way to spend holidays together?",
  "Do you like planning mini-adventures?",
  "Favorite way to surprise each other?",
  "Do you enjoy morning walks with coffee?",
  "Favorite shared hobby?",
  "Do you like giving compliments randomly?",
  "Favorite way to show affection unexpectedly?",
  "Do you enjoy watching sunsets together?",
  "Favorite relaxing activity together?",
  "Do you like sharing favorite books?",
  "Favorite way to celebrate small achievements?",
  "Do you enjoy exploring new places together?",
  "Favorite way to express love creatively?",
  "Do you like making handmade gifts?",
  "Favorite spot for cozy reading together?",
  "Do you enjoy planning future goals together?",
  "Favorite way to unwind in the evening?",
  "Do you like cooking together on weekends?",
  "Favorite way to spend Sunday mornings?",
  "Do you enjoy singing along to music together?",
  "Favorite way to show love without words?",
  "Do you like creating surprises for each other?",
  "Favorite quiet evening routine?",
  "Do you enjoy trying new activities together?",
  "Favorite way to celebrate an accomplishment?",
  "Do you like exchanging small gifts randomly?",
  "Favorite way to spend time together at home?",
  "Do you enjoy outdoor picnics?",
  "Favorite way to enjoy lazy mornings together?",
  "Do you like leaving notes in unexpected places?",
  "Favorite way to make each other laugh?",
  "Do you enjoy late-night conversations?",
  "Favorite way to express gratitude?",
  "Do you like planning trips together?",
  "Favorite way to connect emotionally?",
  "Do you enjoy weekend road trips?",
  "Favorite way to spend cozy nights?",
  "Do you like planning surprise dates?",
  "Favorite activity to do together indoors?",
  "Do you enjoy sharing favorite memories?",
  "Favorite way to show affection daily?",
  "Do you like morning rituals together?",
  "Favorite way to celebrate milestones creatively?",
  "Do you enjoy spontaneous fun activities?",
  "Favorite way to support each other?",
  "Do you like creative date nights at home?",
  "Favorite way to send love messages unexpectedly?",
  "Do you enjoy planning couple projects?",
  "Favorite shared outdoor activity?",
  "Do you like baking or cooking together?",
  "Favorite way to make each other feel special?",
  "Do you enjoy quiet nights together?",
  "Favorite way to express love physically?",
  "Do you like exchanging handwritten notes",
  "Favorite way to celebrate anniversaries together?",
  "Do you enjoy early morning cuddles?",
  "Favorite way to spend lazy afternoons?",
  "Do you like planning fun weekends?",
  "Favorite romantic song to share?",
  "Do you enjoy evening walks together?",
  "Favorite way to spend holidays creatively?",
  "Do you like leaving sweet notes for each other?",
  "Favorite couple activity on rainy days?",
  "Do you enjoy watching movies together?",
  "Favorite way to surprise your partner?",
  "Do you like sending love texts randomly?",
  "Favorite indoor activity together?",
  "Do you enjoy stargazing at night?",
  "Favorite way to spend a cozy evening?",
  "Do you like planning trips together?",
  "Favorite playful activity as a couple?",
  "Do you enjoy cooking new recipes together?",
  "Favorite way to relax on weekends?",
  "Do you like sharing secret messages?",
  "Favorite way to connect emotionally?",
  "Do you enjoy singing together?",
  "Favorite way to start the day together?",
  "Do you like writing love letters?",
  "Favorite spontaneous adventure?",
  "Do you enjoy baking together?",
  "Favorite quiet activity at home?",
  "Do you like sharing favorite memories?",
  "Favorite way to celebrate small wins?",
  "Do you enjoy morning walks?",
  "Favorite way to make your partner smile?",
  "Do you like exchanging gifts unexpectedly?",
  "Favorite cozy corner at home?",
  "Do you enjoy planning surprises?",
  "Favorite way to spend evenings together?",
  "Do you like watching sunsets?",
  "Favorite way to express love creatively?",
  "Do you enjoy playing games together?",
  "Favorite romantic movie to watch together?",
  "Do you like late-night talks?",
  "Favorite way to celebrate birthdays?",
  "Do you enjoy creating couple traditions?",
  "Favorite way to spend weekend mornings?",
  "Do you like planning date nights?",
  "Favorite way to connect after a long day?",
  "Do you enjoy spontaneous picnics?",
  "Favorite shared hobby?",
  "Do you like giving compliments randomly?",
  "Favorite way to laugh together?",
  "Do you enjoy planning future adventures?",
  "Favorite way to show affection physically?",
  "Do you like writing little notes for each other?",
  "Favorite way to unwind in the evening?",
  "Do you enjoy exploring new places?",
  "Favorite activity to do on weekends?",
  "Do you like sharing favorite books?",
  "Favorite way to celebrate milestones?",
  "Do you enjoy cooking together on weekends?",
  "Favorite way to express love daily?",
  "Do you like morning cuddles?",
  "Favorite way to spend cozy nights?",
  "Do you enjoy decorating together?",
  "Favorite playful activity together?",
  "Do you like exchanging handwritten notes?",
  "Favorite way to support each other emotionally?",
  "Do you enjoy late-night drives?",
  "Favorite way to make memories together?",
  "Do you like sending voice messages?",
  "Favorite way to spend Sundays together?",
  "Do you enjoy watching sunrises?",
  "Favorite way to celebrate achievements?",
  "Do you like planning couple projects?",
  "Favorite way to connect emotionally after work?",
  "Do you enjoy creative date nights?",
  "Favorite relaxing activity together?",
  "Do you like sending cute messages?",
  "Favorite way to share laughter?",
  "Do you enjoy spontaneous fun activities?",
  "Favorite way to make each other feel special?",
  "Do you like planning romantic surprises?",
  "Favorite way to express gratitude?",
  "Do you enjoy baking or cooking new meals together?",
  "Favorite couple game to play?",
  "Do you like morning rituals together?",
  "Favorite way to celebrate love creatively?",
  "Do you enjoy storytelling together?",
  "Favorite way to unwind after a busy day?",
  "Do you like decorating for festive seasons?",
  "Favorite indoor activity to enjoy together?",
  "Do you enjoy sharing songs or playlists?",
  "Favorite way to send a love note?",
  "Do you like planning mini-adventures?",
  "Favorite romantic breakfast idea?",
  "Do you enjoy evening walks in the park?",
  "Favorite way to surprise your partner?",
  "Do you like exchanging small gifts randomly?",
  "Favorite playful moment together?",
  "Do you enjoy singing or dancing together?",
  "Favorite way to make each other laugh unexpectedly?",
  "Do you like quiet nights at home together?",
  "Favorite shared hobby for fun?",
  "Do you enjoy late-night talks in bed?",
  "Favorite way to celebrate relationship milestones?",
  "Do you like planning spontaneous trips?",
  "Favorite cozy indoor activity?",
  "Do you enjoy exploring new restaurants together?",
  "Favorite way to connect during busy days?",
  "Do you like making handmade gifts?",
  "Favorite way to spend holidays creatively?",
  "Do you enjoy morning coffee together?",
  "Favorite way to show love without words?",
  "Do you like creative surprises?",
  "Favorite way to spend an evening together?",
  "Do you enjoy writing love notes?",
  "Favorite shared memory?",
  "Do you like celebrating small achievements together?",
  "Favorite playful activity to do together?",
  "Do you enjoy watching romantic movies?",
  "Favorite way to express love physically?",
  "Do you like exchanging sweet messages during the day?",
  "Favorite way to spend quiet mornings together?",
  "Do you enjoy planning couple activities?",
  "Favorite indoor game to play together?",
  "Do you like spontaneous gifts for each other?",
  "Favorite way to connect emotionally at night?",
  "Do you enjoy sharing favorite meals together?",
  "Favorite way to unwind together after work?",
  "Do you like making each other laugh daily?",
  "Favorite romantic gesture?",
  "Do you enjoy long walks together?",
  "Favorite way to celebrate each other’s achievements?",
  "Do you like leaving surprise notes?",
  "Favorite cozy spot for both of you?",
  "Do you enjoy weekend adventures together?",
  "Favorite way to start the day as a couple?",
  "Do you like baking or cooking for each other?",
  "Favorite playful activity indoors?",
  "Do you enjoy late-night phone calls?",
  "Favorite way to celebrate love creatively?",
  "Do you like planning couple outings?",
  "Favorite relaxing activity after work?",
  "Do you enjoy sharing hobbies together?",
  "Favorite way to spend quiet evenings together?",
  "Do you like sharing music playlists?",
  "Favorite way to start a weekend morning?",
  "Do you enjoy morning stretches together?",
  "Favorite way to celebrate a new achievement?",
  "Do you like giving unexpected gifts?",
  "Favorite spot for cozy cuddles?",
  "Do you enjoy listening to audiobooks together?",
  "Favorite way to reconnect after a busy day?",
  "Do you like planning surprise dates?",
  "Favorite couple photo pose?",
  "Do you enjoy walking hand-in-hand?",
  "Favorite way to relax on Sundays?",
  "Do you like cooking themed meals together?",
  "Favorite way to celebrate anniversaries at home?",
  "Do you enjoy late-night drives together?",
  "Favorite shared hobby for weekends?",
  "Do you like decorating for holidays together?",
  "Favorite way to motivate each other?",
  "Do you enjoy morning coffee rituals?",
  "Favorite way to send love messages?",
  "Do you like making scrapbooks together?",
  "Favorite shared adventure memory?",
  "Do you enjoy learning new skills together?",
  "Favorite quiet activity for rainy days?",
  "Do you like leaving surprise notes for each other?",
  "Favorite way to express affection physically?",
  "Do you enjoy morning walks in nature?",
  "Favorite way to celebrate small wins together?",
  "Do you like taking spontaneous trips?",
  "Favorite way to unwind after work?",
  "Do you enjoy creating art together?",
  "Favorite romantic breakfast idea?",
  "Do you like dancing at home together?",
  "Favorite way to support each other emotionally?",
  "Do you enjoy watching sunrises together?",
  "Favorite way to spend a cozy night in?",
  "Do you like sharing your favorite snacks?",
  "Favorite way to say 'I love you' creatively?",
  "Do you enjoy stargazing together?",
  "Favorite memory from a trip together?",
  "Do you like sending cute voice notes?",
  "Favorite way to show appreciation daily?",
  "Do you enjoy trying new restaurants together?",
  "Favorite couple game to play?",
  "Do you like morning cuddles?",
  "Favorite way to celebrate birthdays creatively?",
  "Do you enjoy watching movies under blankets?",
  "Favorite way to cheer each other up?",
  "Do you like creating traditions together?",
  "Favorite quiet weekend activity?",
  "Do you enjoy taking photos of each other?",
  "Favorite way to connect after a long day?",
  "Do you like sending handwritten letters?",
  "Favorite activity to do together outdoors?",
  "Do you enjoy dancing in the living room?",
  "Favorite way to spend holidays together?",
  "Do you like planning mini-adventures?",
  "Favorite way to surprise each other?",
  "Do you enjoy morning walks with coffee?",
  "Favorite shared hobby?",
  "Do you like giving compliments randomly?",
  "Favorite way to show affection unexpectedly?",
  "Do you enjoy watching sunsets together?",
  "Favorite relaxing activity together?",
  "Do you like sharing favorite books?",
  "Favorite way to celebrate small achievements?",
  "Do you enjoy exploring new places together?",
  "Favorite way to express love creatively?",
  "Do you like making handmade gifts?",
  "Favorite spot for cozy reading together?",
  "Do you enjoy planning future goals together?",
  "Favorite way to unwind in the evening?",
  "Do you like cooking together on weekends?",
  "Favorite way to spend Sunday mornings?",
  "Do you enjoy singing along to music together?",
  "Favorite way to show love without words?",
  "Do you like creating surprises for each other?",
  "Favorite quiet evening routine?",
  "Do you enjoy trying new activities together?",
  "Favorite way to celebrate an accomplishment?",
  "Do you like exchanging small gifts randomly?",
  "Favorite way to spend time together at home?",
  "Do you enjoy outdoor picnics?",
  "Favorite way to enjoy lazy mornings together?",
  "Do you like leaving notes in unexpected places?",
  "Favorite way to make each other laugh?",
  "Do you enjoy late-night conversations?",
  "Favorite way to express gratitude?",
  "Do you like planning trips together?",
  "Favorite way to connect emotionally?",
  "Do you enjoy weekend road trips?",
  "Favorite way to spend cozy nights?",
  "Do you like planning surprise dates?",
  "Favorite activity to do together indoors?",
  "Do you enjoy sharing favorite memories?",
  "Favorite way to show affection daily?",
  "Do you like morning rituals together?",
  "Favorite way to celebrate milestones creatively?",
  "Do you enjoy spontaneous fun activities?",
  "Favorite way to support each other?",
  "Do you like creative date nights at home?",
  "Favorite way to send love messages unexpectedly?",
  "Do you enjoy planning couple projects?",
  "Favorite shared outdoor activity?",
  "Do you like baking or cooking together?",
  "Favorite way to make each other feel special?",
  "Do you enjoy quiet nights together?",
  "Favorite way to express love physically?",
  "Do you like exchanging handwritten notes?"
]
